# Generated by Django 2.2.6 on 2019-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
